### PR TITLE
Python compatibility

### PR DESCRIPTION
**Pull request by chaosct**
I had to modify both the interface file and the Makefile in order to generate valid Python bindings and C++ code:
- Passing the language used to swig, in order to deactivate parts of the interface file that make no sense for different languages (yes, swig complains when encountering `%luacode` while compiling for Python).
- Python specific renaming rules for overloaded operators.
- Python specific workarounds needed to compile in MinGW and OSX.
- An output dir for generated Python files can be specified with `DEST_LANG_DIR`

I also added a way to change the _style_ of the bindings:
- Configurable module name by passing `MODULE_NAME`
- Optional stripping of "of" prefix in functions, classes, constants and enums by passing `RENAME`
- In the Makefile the default for Python is `MODULE_NAME=openframeworks` and `RENAME=false`, since I feel that this is more _Pythonic_.

If you are OK with these changes I can modify the documentation accordingly.

### CODE REVIEW

**Comment by danomatika** [comment]
Yeah this looks good. Glad to see it didn't take much to work for Python. I might make a few small (anal) changes but overall it looks good.

**Comment by danomatika** [comment]
I'll wait on this until you give me the go signal.

**Comment by chaosct** [comment]
Yes thanks! I probably won't have time for that until next week.

**Comment by chaosct** [comment]
I think that's it.

**Comment by danomatika** [comment]
I made a few small changes, the main one was `RENAME` -> `OF_SWIG_RENAME` to be a bit more explicit.

**Pull request merged**
